import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
console.log('Seed lancé !');
const prisma = new PrismaClient();

/*
 * Règle métier crédits :
 * - Lors d'une réservation : 2 crédits vont à l'admin (plateforme), le reste au chauffeur.
 * - Lors d'une annulation par le chauffeur : chaque passager est remboursé, le chauffeur et l'admin sont débités de leur part.
 * - L'admin (pseudo: 'admin', role_id: 2) doit toujours exister dans la seed.
 */

// Fonction pour hasher les mots de passe
async function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, 10);
}

async function main() {
  // Rôles
  await prisma.role.createMany({
    data: [{ libelle: 'Utilisateur' }, { libelle: 'Administrateur' }, { libelle: 'Employé' }],
  });

  // Hash des mots de passe
  const hashedPasswords = {
    password123: await hashPassword('password123'),
    password456: await hashPassword('password456'),
    password789: await hashPassword('password789'),
    password321: await hashPassword('password321'),
    password654: await hashPassword('password654'),
    password987: await hashPassword('password987'),
    passwordabc: await hashPassword('passwordabc'),
    passworddef: await hashPassword('passworddef'),
    passwordghi: await hashPassword('passwordghi'),
    passwordjkl: await hashPassword('passwordjkl'),
    passwordmno: await hashPassword('passwordmno'),
    passwordpqr: await hashPassword('passwordpqr'),
    passwordstu: await hashPassword('passwordstu'),
    passwordvwx: await hashPassword('passwordvwx'),
    passwordyz1: await hashPassword('passwordyz1'),
    password234: await hashPassword('password234'),
    password567: await hashPassword('password567'),
    password890: await hashPassword('password890'),
    adminpass: await hashPassword('adminpass'),
    employepass: await hashPassword('employepass'),
  };

  // Utilisateurs
  await prisma.utilisateur.createMany({
    data: [
      {
        utilisateur_id: 1,
        civilite: 'M.',
        nom: 'Dupont',
        prenom: 'Jean',
        email: 'jean.dupont@email.com',
        password: hashedPasswords.password123,
        telephone: '0600000001',
        adresse: '1 rue de Paris',
        date_naissance: '1985-01-01',
        pseudo: 'jdupont',
        role_id: 1,
        credit: 20,
      },
      {
        utilisateur_id: 2,
        civilite: 'Mme',
        nom: 'Martin',
        prenom: 'Sophie',
        email: 'sophie.martin@email.com',
        password: hashedPasswords.password456,
        telephone: '0600000002',
        adresse: '2 avenue de Lyon',
        date_naissance: '1990-05-12',
        pseudo: 'smartin',
        role_id: 1,
        credit: 35,
      },
      {
        utilisateur_id: 3,
        civilite: 'M.',
        nom: 'Durand',
        prenom: 'Paul',
        email: 'paul.durand@email.com',
        password: hashedPasswords.password789,
        telephone: '0600000003',
        adresse: '3 rue de Lille',
        date_naissance: '1988-03-22',
        pseudo: 'pdurand',
        role_id: 1,
        credit: 5,
      },
      {
        utilisateur_id: 4,
        civilite: 'Mme',
        nom: 'Bernard',
        prenom: 'Julie',
        email: 'julie.bernard@email.com',
        password: hashedPasswords.password321,
        telephone: '0600000004',
        adresse: '4 avenue de Bordeaux',
        date_naissance: '1992-07-18',
        pseudo: 'jbernard',
        role_id: 1,
        credit: 0,
      },
      {
        utilisateur_id: 5,
        civilite: 'M.',
        nom: 'Petit',
        prenom: 'Luc',
        email: 'luc.petit@email.com',
        password: hashedPasswords.password654,
        telephone: '0600000005',
        adresse: '5 rue de Nice',
        date_naissance: '1987-11-30',
        pseudo: 'lpetit',
        role_id: 1,
        credit: 50,
      },
      {
        utilisateur_id: 6,
        civilite: 'Mme',
        nom: 'Robert',
        prenom: 'Claire',
        email: 'claire.robert@email.com',
        password: hashedPasswords.password987,
        telephone: '0600000006',
        adresse: '6 avenue de Nantes',
        date_naissance: '1991-09-14',
        pseudo: 'crobert',
        role_id: 1,
        credit: 12,
      },
      {
        utilisateur_id: 7,
        civilite: 'M.',
        nom: 'Richard',
        prenom: 'Hugo',
        email: 'hugo.richard@email.com',
        password: hashedPasswords.passwordabc,
        telephone: '0600000007',
        adresse: '7 rue de Rennes',
        date_naissance: '1986-05-25',
        pseudo: 'hrichard',
        role_id: 1,
        credit: 8,
      },
      {
        utilisateur_id: 8,
        civilite: 'Mme',
        nom: 'Simon',
        prenom: 'Emma',
        email: 'emma.simon@email.com',
        password: hashedPasswords.passworddef,
        telephone: '0600000008',
        adresse: '8 avenue de Toulouse',
        date_naissance: '1993-12-02',
        pseudo: 'esimon',
        role_id: 1,
        credit: 25,
      },
      {
        utilisateur_id: 9,
        civilite: 'M.',
        nom: 'Lefevre',
        prenom: 'Louis',
        email: 'louis.lefevre@email.com',
        password: hashedPasswords.passwordghi,
        telephone: '0600000009',
        adresse: '9 rue de Strasbourg',
        date_naissance: '1989-04-10',
        pseudo: 'llefevre',
        role_id: 1,
        credit: 18,
      },
      {
        utilisateur_id: 10,
        civilite: 'Mme',
        nom: 'Moreau',
        prenom: 'Alice',
        email: 'alice.moreau@email.com',
        password: hashedPasswords.passwordjkl,
        telephone: '0600000010',
        adresse: '10 avenue de Montpellier',
        date_naissance: '1994-08-21',
        pseudo: 'amoreau',
        role_id: 1,
        credit: 40,
      },
      {
        utilisateur_id: 11,
        civilite: 'M.',
        nom: 'Garcia',
        prenom: 'Pierre',
        email: 'pierre.garcia@email.com',
        password: hashedPasswords.passwordmno,
        telephone: '0600000011',
        adresse: '11 rue de Dijon',
        date_naissance: '1985-02-15',
        pseudo: 'pgarcia',
        role_id: 1,
        credit: 22,
      },
      {
        utilisateur_id: 12,
        civilite: 'Mme',
        nom: 'Martinez',
        prenom: 'Laura',
        email: 'laura.martinez@email.com',
        password: hashedPasswords.passwordpqr,
        telephone: '0600000012',
        adresse: '12 avenue de Limoges',
        date_naissance: '1990-06-19',
        pseudo: 'lmartinez',
        role_id: 1,
        credit: 15,
      },
      {
        utilisateur_id: 13,
        civilite: 'M.',
        nom: 'Lopez',
        prenom: 'Antoine',
        email: 'antoine.lopez@email.com',
        password: hashedPasswords.passwordstu,
        telephone: '0600000013',
        adresse: '13 rue de Brest',
        date_naissance: '1988-10-05',
        pseudo: 'alopez',
        role_id: 1,
        credit: 7,
      },
      {
        utilisateur_id: 14,
        civilite: 'Mme',
        nom: 'Gonzalez',
        prenom: 'Camille',
        email: 'camille.gonzalez@email.com',
        password: hashedPasswords.passwordvwx,
        telephone: '0600000014',
        adresse: '14 avenue de Reims',
        date_naissance: '1992-01-28',
        pseudo: 'cgonzalez',
        role_id: 1,
        credit: 30,
      },
      {
        utilisateur_id: 15,
        civilite: 'M.',
        nom: 'Perez',
        prenom: 'Lucas',
        email: 'lucas.perez@email.com',
        password: hashedPasswords.passwordyz1,
        telephone: '0600000015',
        adresse: '15 rue de Metz',
        date_naissance: '1987-07-13',
        pseudo: 'lperez',
        role_id: 1,
        credit: 19,
      },
      {
        utilisateur_id: 16,
        civilite: 'Mme',
        nom: 'Sanchez',
        prenom: 'Léa',
        email: 'lea.sanchez@email.com',
        password: hashedPasswords.password234,
        telephone: '0600000016',
        adresse: '16 avenue de Tours',
        date_naissance: '1991-03-09',
        pseudo: 'lsanchez',
        role_id: 1,
        credit: 11,
      },
      {
        utilisateur_id: 17,
        civilite: 'M.',
        nom: 'Roux',
        prenom: 'Maxime',
        email: 'maxime.roux@email.com',
        password: hashedPasswords.password567,
        telephone: '0600000017',
        adresse: '17 rue de Pau',
        date_naissance: '1986-09-27',
        pseudo: 'mroux',
        role_id: 1,
        credit: 27,
      },
      {
        utilisateur_id: 18,
        civilite: 'Mme',
        nom: 'Morel',
        prenom: 'Chloé',
        email: 'chloe.morel@email.com',
        password: hashedPasswords.password890,
        telephone: '0600000018',
        adresse: '18 avenue de Perpignan',
        date_naissance: '1993-11-16',
        pseudo: 'cmorel',
        role_id: 1,
        credit: 6,
      },
      {
        utilisateur_id: 19,
        civilite: 'M.',
        nom: 'Fournier',
        prenom: 'Nathan',
        email: 'nathan.fournier@email.com',
        password: hashedPasswords.passwordabc,
        telephone: '0600000019',
        adresse: '19 rue de Mulhouse',
        date_naissance: '1989-02-03',
        pseudo: 'nfournier',
        role_id: 1,
        credit: 13,
      },
      {
        utilisateur_id: 20,
        civilite: 'Mme',
        nom: 'Girard',
        prenom: 'Sarah',
        email: 'sarah.girard@email.com',
        password: hashedPasswords.passworddef,
        telephone: '0600000020',
        adresse: '20 avenue de Caen',
        date_naissance: '1994-05-29',
        pseudo: 'sgirard',
        role_id: 1,
        credit: 17,
      },
      {
        utilisateur_id: 21,
        civilite: 'M.',
        nom: 'Andre',
        prenom: 'Julien',
        email: 'julien.andre@email.com',
        password: hashedPasswords.passwordghi,
        telephone: '0600000021',
        adresse: '21 rue de Nancy',
        date_naissance: '1985-08-11',
        pseudo: 'jandre',
        role_id: 1,
        credit: 21,
      },
      {
        utilisateur_id: 22,
        civilite: 'Mme',
        nom: 'Mercier',
        prenom: 'Eva',
        email: 'eva.mercier@email.com',
        password: hashedPasswords.passwordjkl,
        telephone: '0600000022',
        adresse: '22 avenue de Poitiers',
        date_naissance: '1990-12-23',
        pseudo: 'emercier',
        role_id: 1,
        credit: 9,
      },
      {
        utilisateur_id: 23,
        civilite: 'M.',
        nom: 'Blanc',
        prenom: 'Hugo',
        email: 'hugo.blanc@email.com',
        password: hashedPasswords.passwordmno,
        telephone: '0600000023',
        adresse: '23 rue de Béziers',
        date_naissance: '1988-06-07',
        pseudo: 'hblanc',
        role_id: 1,
        credit: 16,
      },
      {
        utilisateur_id: 24,
        civilite: 'Mme',
        nom: 'Guerin',
        prenom: 'Lina',
        email: 'lina.guerin@email.com',
        password: hashedPasswords.passwordpqr,
        telephone: '0600000024',
        adresse: '24 avenue de Quimper',
        date_naissance: '1992-10-19',
        pseudo: 'lguerin',
        role_id: 1,
        credit: 3,
      },
      {
        utilisateur_id: 25,
        civilite: 'M.',
        nom: 'Boyer',
        prenom: 'Tom',
        email: 'tom.boyer@email.com',
        password: hashedPasswords.passwordstu,
        telephone: '0600000025',
        adresse: '25 rue de Colmar',
        date_naissance: '1987-01-31',
        pseudo: 'tboyer',
        role_id: 1,
        credit: 14,
      },
      {
        utilisateur_id: 26,
        civilite: 'Mme',
        nom: 'Lemoine',
        prenom: 'Anna',
        email: 'anna.lemoine@email.com',
        password: hashedPasswords.passwordvwx,
        telephone: '0600000026',
        adresse: '26 avenue de Tarbes',
        date_naissance: '1991-05-15',
        pseudo: 'alemoine',
        role_id: 1,
        credit: 24,
      },
      {
        utilisateur_id: 27,
        civilite: 'M.',
        nom: 'Faure',
        prenom: 'Enzo',
        email: 'enzo.faure@email.com',
        password: hashedPasswords.passwordyz1,
        telephone: '0600000027',
        adresse: '27 rue de Laval',
        date_naissance: '1986-08-28',
        pseudo: 'efaure',
        role_id: 1,
        credit: 2,
      },
      {
        utilisateur_id: 28,
        civilite: 'Mme',
        nom: 'Carpentier',
        prenom: 'Léonie',
        email: 'leonie.carpentier@email.com',
        password: hashedPasswords.password234,
        telephone: '0600000028',
        adresse: '28 avenue de Chambéry',
        date_naissance: '1993-02-12',
        pseudo: 'lcarpentier',
        role_id: 1,
        credit: 38,
      },
      {
        utilisateur_id: 29,
        civilite: 'M.',
        nom: 'Boucher',
        prenom: 'Axel',
        email: 'axel.boucher@email.com',
        password: hashedPasswords.password567,
        telephone: '0600000029',
        adresse: '29 rue de Vannes',
        date_naissance: '1989-10-04',
        pseudo: 'aboucher',
        role_id: 1,
        credit: 4,
      },
      {
        utilisateur_id: 30,
        civilite: 'Mme',
        nom: 'Muller',
        prenom: 'Jade',
        email: 'jade.muller@email.com',
        password: hashedPasswords.password890,
        telephone: '0600000030',
        adresse: '30 avenue de La Rochelle',
        date_naissance: '1994-03-18',
        pseudo: 'jmuller',
        role_id: 1,
        credit: 23,
      },
      {
        utilisateur_id: 31,
        civilite: 'M.',
        nom: 'Leroy',
        prenom: 'Baptiste',
        email: 'baptiste.leroy@email.com',
        password: hashedPasswords.passwordabc,
        telephone: '0600000031',
        adresse: '31 rue de Saint-Malo',
        date_naissance: '1985-04-14',
        pseudo: 'bleroy',
        role_id: 1,
        credit: 12,
      },
      {
        utilisateur_id: 32,
        civilite: 'Mme',
        nom: 'Roussel',
        prenom: 'Lola',
        email: 'lola.roussel@email.com',
        password: hashedPasswords.passworddef,
        telephone: '0600000032',
        adresse: '32 avenue de Brive',
        date_naissance: '1990-09-26',
        pseudo: 'lroussel',
        role_id: 1,
        credit: 29,
      },
      {
        utilisateur_id: 33,
        civilite: 'M.',
        nom: 'Morin',
        prenom: 'Gabriel',
        email: 'gabriel.morin@email.com',
        password: hashedPasswords.passwordghi,
        telephone: '0600000033',
        adresse: '33 rue de Sète',
        date_naissance: '1988-12-08',
        pseudo: 'gmorin',
        role_id: 1,
        credit: 31,
      },
      {
        utilisateur_id: 34,
        civilite: 'Mme',
        nom: 'Mathieu',
        prenom: 'Léna',
        email: 'lena.mathieu@email.com',
        password: hashedPasswords.passwordjkl,
        telephone: '0600000034',
        adresse: '34 avenue de Bastia',
        date_naissance: '1992-06-20',
        pseudo: 'lmathieu',
        role_id: 1,
        credit: 10,
      },
      {
        utilisateur_id: 35,
        civilite: 'M.',
        nom: 'Clement',
        prenom: 'Noah',
        email: 'noah.clement@email.com',
        password: hashedPasswords.passwordmno,
        telephone: '0600000035',
        adresse: '35 rue de Carcassonne',
        date_naissance: '1987-03-03',
        pseudo: 'nclement',
        role_id: 1,
        credit: 26,
      },
      {
        utilisateur_id: 36,
        civilite: 'Mme',
        nom: 'Gauthier',
        prenom: 'Mila',
        email: 'mila.gauthier@email.com',
        password: hashedPasswords.passwordpqr,
        telephone: '0600000036',
        adresse: '36 avenue de Chalon',
        date_naissance: '1991-07-17',
        pseudo: 'mgauthier',
        role_id: 1,
        credit: 15,
      },
      {
        utilisateur_id: 37,
        civilite: 'M.',
        nom: 'Jean',
        prenom: 'Ethan',
        email: 'ethan.jean@email.com',
        password: hashedPasswords.passwordstu,
        telephone: '0600000037',
        adresse: '37 rue de Périgueux',
        date_naissance: '1986-11-01',
        pseudo: 'ejean',
        role_id: 1,
        credit: 20,
      },
      {
        utilisateur_id: 38,
        civilite: 'Mme',
        nom: 'Masson',
        prenom: 'Rose',
        email: 'rose.masson@email.com',
        password: hashedPasswords.passwordvwx,
        telephone: '0600000038',
        adresse: '38 avenue de Montauban',
        date_naissance: '1993-04-25',
        pseudo: 'rmasson',
        role_id: 1,
        credit: 13,
      },
      {
        utilisateur_id: 39,
        civilite: 'M.',
        nom: 'Marchand',
        prenom: 'Adam',
        email: 'adam.marchand@email.com',
        password: hashedPasswords.passwordyz1,
        telephone: '0600000039',
        adresse: '39 rue de Valence',
        date_naissance: '1989-06-13',
        pseudo: 'amarchand',
        role_id: 1,
        credit: 17,
      },
      {
        utilisateur_id: 40,
        civilite: 'Mme',
        nom: 'Duval',
        prenom: 'Lina',
        email: 'lina.duval@email.com',
        password: hashedPasswords.password234,
        telephone: '0600000040',
        adresse: '40 avenue de Gap',
        date_naissance: '1994-10-07',
        pseudo: 'lduval',
        role_id: 1,
        credit: 22,
      },
      {
        utilisateur_id: 41,
        civilite: 'M.',
        nom: 'Admin',
        prenom: 'Super',
        email: 'admin@email.com',
        password: hashedPasswords.adminpass,
        telephone: '0600000041',
        adresse: "41 rue de l'Admin",
        date_naissance: '1980-01-01',
        pseudo: 'admin',
        role_id: 2,
        credit: 100,
      },
      {
        utilisateur_id: 42,
        civilite: 'M.',
        nom: 'Employe',
        prenom: 'Staff',
        email: 'employe@email.com',
        password: hashedPasswords.employepass,
        telephone: '0600000042',
        adresse: "42 rue de l'Employé",
        date_naissance: '1982-02-02',
        pseudo: 'employe',
        role_id: 3,
        credit: 20,
      },
    ],
  });

  // Marques
  await prisma.marque.createMany({
    data: [
      { libelle: 'Renault' },
      { libelle: 'Peugeot' },
      { libelle: 'Citroën' },
      { libelle: 'Volkswagen' },
      { libelle: 'Toyota' },
      { libelle: 'Ford' },
      { libelle: 'Opel' },
      { libelle: 'Fiat' },
      { libelle: 'BMW' },
      { libelle: 'Mercedes' },
      { libelle: 'Audi' },
      { libelle: 'Kia' },
      { libelle: 'Hyundai' },
      { libelle: 'Seat' },
      { libelle: 'Dacia' },
      { libelle: 'Nissan' },
      { libelle: 'Mazda' },
      { libelle: 'Honda' },
      { libelle: 'Skoda' },
      { libelle: 'Mini' },
      { libelle: 'Volvo' },
      { libelle: 'Suzuki' },
      { libelle: 'Chevrolet' },
      { libelle: 'Jeep' },
      { libelle: 'Lexus' },
      { libelle: 'Mitsubishi' },
      { libelle: 'Subaru' },
      { libelle: 'Alfa Romeo' },
      { libelle: 'Jaguar' },
      { libelle: 'Land Rover' },
      { libelle: 'Porsche' },
    ],
  });

  // Voitures
  await prisma.voiture.createMany({
    data: [
      {
        modele: 'Clio',
        immatriculation: 'AB-123-CD',
        energie: 'Essence',
        couleur: 'Rouge',
        date_premiere_immatriculation: '2015-06-01',
        marque_id: 1,
        utilisateur_id: 1,
      },
      {
        modele: '208',
        immatriculation: 'EF-456-GH',
        energie: 'Diesel',
        couleur: 'Bleu',
        date_premiere_immatriculation: '2018-09-15',
        marque_id: 2,
        utilisateur_id: 2,
      },
      {
        modele: 'C3',
        immatriculation: 'IJ-789-KL',
        energie: 'Essence',
        couleur: 'Blanc',
        date_premiere_immatriculation: '2017-03-10',
        marque_id: 3,
        utilisateur_id: 3,
      },
      {
        modele: 'Golf',
        immatriculation: 'MN-012-OP',
        energie: 'Diesel',
        couleur: 'Noir',
        date_premiere_immatriculation: '2016-11-20',
        marque_id: 4,
        utilisateur_id: 4,
      },
      {
        modele: 'Yaris',
        immatriculation: 'QR-345-ST',
        energie: 'Hybride',
        couleur: 'Gris',
        date_premiere_immatriculation: '2019-08-05',
        marque_id: 5,
        utilisateur_id: 5,
      },
      {
        modele: 'Focus',
        immatriculation: 'UV-678-WX',
        energie: 'Essence',
        couleur: 'Bleu',
        date_premiere_immatriculation: '2014-04-18',
        marque_id: 6,
        utilisateur_id: 6,
      },
      {
        modele: 'Corsa',
        immatriculation: 'YZ-901-AB',
        energie: 'Diesel',
        couleur: 'Rouge',
        date_premiere_immatriculation: '2013-12-30',
        marque_id: 7,
        utilisateur_id: 7,
      },
      {
        modele: 'Panda',
        immatriculation: 'CD-234-EF',
        energie: 'Essence',
        couleur: 'Vert',
        date_premiere_immatriculation: '2012-07-22',
        marque_id: 8,
        utilisateur_id: 8,
      },
      {
        modele: 'Serie 1',
        immatriculation: 'GH-567-IJ',
        energie: 'Diesel',
        couleur: 'Noir',
        date_premiere_immatriculation: '2015-09-14',
        marque_id: 9,
        utilisateur_id: 9,
      },
      {
        modele: 'Classe A',
        immatriculation: 'KL-890-MN',
        energie: 'Essence',
        couleur: 'Blanc',
        date_premiere_immatriculation: '2016-02-27',
        marque_id: 10,
        utilisateur_id: 10,
      },
      {
        modele: 'A3',
        immatriculation: 'OP-123-QR',
        energie: 'Diesel',
        couleur: 'Gris',
        date_premiere_immatriculation: '2017-05-19',
        marque_id: 11,
        utilisateur_id: 11,
      },
      {
        modele: 'Picanto',
        immatriculation: 'ST-456-UV',
        energie: 'Essence',
        couleur: 'Bleu',
        date_premiere_immatriculation: '2018-10-23',
        marque_id: 12,
        utilisateur_id: 12,
      },
      {
        modele: 'i20',
        immatriculation: 'WX-789-YZ',
        energie: 'Hybride',
        couleur: 'Rouge',
        date_premiere_immatriculation: '2019-01-11',
        marque_id: 13,
        utilisateur_id: 13,
      },
      {
        modele: 'Ibiza',
        immatriculation: 'AB-234-CD',
        energie: 'Essence',
        couleur: 'Noir',
        date_premiere_immatriculation: '2014-06-16',
        marque_id: 14,
        utilisateur_id: 14,
      },
      {
        modele: 'Sandero',
        immatriculation: 'EF-567-GH',
        energie: 'Diesel',
        couleur: 'Blanc',
        date_premiere_immatriculation: '2013-03-29',
        marque_id: 15,
        utilisateur_id: 15,
      },
    ],
  });

  // Covoiturages (50)
  await prisma.covoiturage.createMany({
    data: [
      {
        date_depart: '2025-06-10',
        heure_depart: '12:00:00',
        lieu_depart: 'Paris',
        date_arrivee: '2025-06-10',
        heure_arrivee: '16:00:00',
        lieu_arrivee: 'Lyon',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 25.0,
        voiture_id: 1,
        utilisateur_id: 1,
      },
      {
        date_depart: '2025-06-12',
        heure_depart: '14:30:00',
        lieu_depart: 'Lyon',
        date_arrivee: '2025-06-12',
        heure_arrivee: '18:30:00',
        lieu_arrivee: 'Marseille',
        statut: 'ouvert',
        nb_place: 2,
        prix_personne: 5,
        voiture_id: 2,
        utilisateur_id: 2,
      },
      {
        date_depart: '2025-06-13',
        heure_depart: '09:00:00',
        lieu_depart: 'Marseille',
        date_arrivee: '2025-06-13',
        heure_arrivee: '13:00:00',
        lieu_arrivee: 'Nice',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 6,
        voiture_id: 3,
        utilisateur_id: 3,
      },
      {
        date_depart: '2025-06-14',
        heure_depart: '16:00:00',
        lieu_depart: 'Nice',
        date_arrivee: '2025-06-14',
        heure_arrivee: '20:00:00',
        lieu_arrivee: 'Toulouse',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 10,
        voiture_id: 4,
        utilisateur_id: 4,
      },
      {
        date_depart: '2025-06-15',
        heure_depart: '11:00:00',
        lieu_depart: 'Toulouse',
        date_arrivee: '2025-06-15',
        heure_arrivee: '15:00:00',
        lieu_arrivee: 'Bordeaux',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 12,
        voiture_id: 5,
        utilisateur_id: 5,
      },
      {
        date_depart: '2025-06-16',
        heure_depart: '15:00:00',
        lieu_depart: 'Bordeaux',
        date_arrivee: '2025-06-16',
        heure_arrivee: '19:00:00',
        lieu_arrivee: 'Nantes',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 5,
        voiture_id: 6,
        utilisateur_id: 6,
      },
      {
        date_depart: '2025-06-17',
        heure_depart: '10:00:00',
        lieu_depart: 'Nantes',
        date_arrivee: '2025-06-17',
        heure_arrivee: '14:00:00',
        lieu_arrivee: 'Rennes',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 10,
        voiture_id: 7,
        utilisateur_id: 7,
      },
      {
        date_depart: '2025-06-18',
        heure_depart: '13:00:00',
        lieu_depart: 'Rennes',
        date_arrivee: '2025-06-18',
        heure_arrivee: '17:00:00',
        lieu_arrivee: 'Lille',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 10,
        voiture_id: 8,
        utilisateur_id: 8,
      },
      {
        date_depart: '2025-06-19',
        heure_depart: '17:00:00',
        lieu_depart: 'Lille',
        date_arrivee: '2025-06-19',
        heure_arrivee: '21:00:00',
        lieu_arrivee: 'Strasbourg',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 9,
        utilisateur_id: 9,
      },
      {
        date_depart: '2025-06-20',
        heure_depart: '12:00:00',
        lieu_depart: 'Strasbourg',
        date_arrivee: '2025-06-20',
        heure_arrivee: '16:00:00',
        lieu_arrivee: 'Metz',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 5,
        voiture_id: 10,
        utilisateur_id: 10,
      },
      {
        date_depart: '2025-06-21',
        heure_depart: '08:00:00',
        lieu_depart: 'Metz',
        date_arrivee: '2025-06-21',
        heure_arrivee: '12:00:00',
        lieu_arrivee: 'Nancy',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 11,
        utilisateur_id: 11,
      },
      {
        date_depart: '2025-06-22',
        heure_depart: '14:00:00',
        lieu_depart: 'Nancy',
        date_arrivee: '2025-06-22',
        heure_arrivee: '18:00:00',
        lieu_arrivee: 'Dijon',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 12,
        utilisateur_id: 12,
      },
      {
        date_depart: '2025-06-23',
        heure_depart: '16:00:00',
        lieu_depart: 'Dijon',
        date_arrivee: '2025-06-23',
        heure_arrivee: '20:00:00',
        lieu_arrivee: 'Besançon',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 8,
        voiture_id: 13,
        utilisateur_id: 13,
      },
      {
        date_depart: '2025-06-24',
        heure_depart: '09:00:00',
        lieu_depart: 'Besançon',
        date_arrivee: '2025-06-24',
        heure_arrivee: '13:00:00',
        lieu_arrivee: 'Annecy',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 5,
        voiture_id: 14,
        utilisateur_id: 14,
      },
      {
        date_depart: '2025-06-25',
        heure_depart: '11:00:00',
        lieu_depart: 'Annecy',
        date_arrivee: '2025-06-25',
        heure_arrivee: '15:00:00',
        lieu_arrivee: 'Grenoble',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 5,
        voiture_id: 15,
        utilisateur_id: 15,
      },
      {
        date_depart: '2025-06-26',
        heure_depart: '15:00:00',
        lieu_depart: 'Grenoble',
        date_arrivee: '2025-06-26',
        heure_arrivee: '19:00:00',
        lieu_arrivee: 'Chambéry',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 4,
        voiture_id: 1,
        utilisateur_id: 1,
      },
      {
        date_depart: '2025-06-27',
        heure_depart: '10:00:00',
        lieu_depart: 'Chambéry',
        date_arrivee: '2025-06-27',
        heure_arrivee: '14:00:00',
        lieu_arrivee: 'Valence',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 6,
        voiture_id: 2,
        utilisateur_id: 2,
      },
      {
        date_depart: '2025-06-28',
        heure_depart: '13:00:00',
        lieu_depart: 'Valence',
        date_arrivee: '2025-06-28',
        heure_arrivee: '17:00:00',
        lieu_arrivee: 'Avignon',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 9,
        voiture_id: 3,
        utilisateur_id: 3,
      },
      {
        date_depart: '2025-06-29',
        heure_depart: '17:00:00',
        lieu_depart: 'Avignon',
        date_arrivee: '2025-06-29',
        heure_arrivee: '21:00:00',
        lieu_arrivee: 'Montpellier',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 9,
        voiture_id: 4,
        utilisateur_id: 4,
      },
      {
        date_depart: '2025-06-30',
        heure_depart: '12:00:00',
        lieu_depart: 'Montpellier',
        date_arrivee: '2025-06-30',
        heure_arrivee: '16:00:00',
        lieu_arrivee: 'Perpignan',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 10,
        voiture_id: 5,
        utilisateur_id: 5,
      },
      {
        date_depart: '2025-07-01',
        heure_depart: '08:00:00',
        lieu_depart: 'Perpignan',
        date_arrivee: '2025-07-01',
        heure_arrivee: '12:00:00',
        lieu_arrivee: 'Narbonne',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 12,
        voiture_id: 6,
        utilisateur_id: 6,
      },
      {
        date_depart: '2025-07-02',
        heure_depart: '14:00:00',
        lieu_depart: 'Narbonne',
        date_arrivee: '2025-07-02',
        heure_arrivee: '18:00:00',
        lieu_arrivee: 'Carcassonne',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 5,
        voiture_id: 7,
        utilisateur_id: 7,
      },
      {
        date_depart: '2025-07-03',
        heure_depart: '16:00:00',
        lieu_depart: 'Carcassonne',
        date_arrivee: '2025-07-03',
        heure_arrivee: '20:00:00',
        lieu_arrivee: 'Albi',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 15,
        voiture_id: 8,
        utilisateur_id: 8,
      },
      {
        date_depart: '2025-07-04',
        heure_depart: '09:00:00',
        lieu_depart: 'Albi',
        date_arrivee: '2025-07-04',
        heure_arrivee: '13:00:00',
        lieu_arrivee: 'Montauban',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 6,
        voiture_id: 9,
        utilisateur_id: 9,
      },
      {
        date_depart: '2025-07-05',
        heure_depart: '11:00:00',
        lieu_depart: 'Montauban',
        date_arrivee: '2025-07-05',
        heure_arrivee: '15:00:00',
        lieu_arrivee: 'Agen',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 10,
        utilisateur_id: 10,
      },
      {
        date_depart: '2025-07-06',
        heure_depart: '15:00:00',
        lieu_depart: 'Agen',
        date_arrivee: '2025-07-06',
        heure_arrivee: '19:00:00',
        lieu_arrivee: 'Pau',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 11,
        utilisateur_id: 11,
      },
      {
        date_depart: '2025-07-07',
        heure_depart: '10:00:00',
        lieu_depart: 'Pau',
        date_arrivee: '2025-07-07',
        heure_arrivee: '14:00:00',
        lieu_arrivee: 'Tarbes',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 12,
        utilisateur_id: 12,
      },
      {
        date_depart: '2025-07-08',
        heure_depart: '13:00:00',
        lieu_depart: 'Tarbes',
        date_arrivee: '2025-07-08',
        heure_arrivee: '17:00:00',
        lieu_arrivee: 'Lourdes',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 6,
        voiture_id: 13,
        utilisateur_id: 13,
      },
      {
        date_depart: '2025-07-09',
        heure_depart: '17:00:00',
        lieu_depart: 'Lourdes',
        date_arrivee: '2025-07-09',
        heure_arrivee: '21:00:00',
        lieu_arrivee: 'Bayonne',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 3,
        voiture_id: 14,
        utilisateur_id: 14,
      },
      {
        date_depart: '2025-07-10',
        heure_depart: '12:00:00',
        lieu_depart: 'Bayonne',
        date_arrivee: '2025-07-10',
        heure_arrivee: '16:00:00',
        lieu_arrivee: 'Biarritz',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 6,
        voiture_id: 15,
        utilisateur_id: 15,
      },
      {
        date_depart: '2025-07-11',
        heure_depart: '08:00:00',
        lieu_depart: 'Biarritz',
        date_arrivee: '2025-07-11',
        heure_arrivee: '12:00:00',
        lieu_arrivee: 'Anglet',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 10,
        voiture_id: 1,
        utilisateur_id: 1,
      },
      {
        date_depart: '2025-07-12',
        heure_depart: '14:00:00',
        lieu_depart: 'Anglet',
        date_arrivee: '2025-07-12',
        heure_arrivee: '18:00:00',
        lieu_arrivee: 'Dax',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 14,
        voiture_id: 2,
        utilisateur_id: 2,
      },
      {
        date_depart: '2025-07-13',
        heure_depart: '16:00:00',
        lieu_depart: 'Dax',
        date_arrivee: '2025-07-13',
        heure_arrivee: '20:00:00',
        lieu_arrivee: 'Mont-de-Marsan',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 5,
        voiture_id: 3,
        utilisateur_id: 3,
      },
      {
        date_depart: '2025-07-14',
        heure_depart: '09:00:00',
        lieu_depart: 'Mont-de-Marsan',
        date_arrivee: '2025-07-14',
        heure_arrivee: '13:00:00',
        lieu_arrivee: "Aire-sur-l'Adour",
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 6,
        voiture_id: 4,
        utilisateur_id: 4,
      },
      {
        date_depart: '2025-07-15',
        heure_depart: '11:00:00',
        lieu_depart: "Aire-sur-l'Adour",
        date_arrivee: '2025-07-15',
        heure_arrivee: '15:00:00',
        lieu_arrivee: 'Tarbes',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 5,
        utilisateur_id: 5,
      },
      {
        date_depart: '2025-07-16',
        heure_depart: '15:00:00',
        lieu_depart: 'Tarbes',
        date_arrivee: '2025-07-16',
        heure_arrivee: '19:00:00',
        lieu_arrivee: 'Pau',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 6,
        utilisateur_id: 6,
      },
      {
        date_depart: '2025-07-17',
        heure_depart: '10:00:00',
        lieu_depart: 'Pau',
        date_arrivee: '2025-07-17',
        heure_arrivee: '14:00:00',
        lieu_arrivee: 'Agen',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 10,
        voiture_id: 7,
        utilisateur_id: 7,
      },
      {
        date_depart: '2025-07-18',
        heure_depart: '13:00:00',
        lieu_depart: 'Agen',
        date_arrivee: '2025-07-18',
        heure_arrivee: '17:00:00',
        lieu_arrivee: 'Montauban',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 9,
        voiture_id: 8,
        utilisateur_id: 8,
      },
      {
        date_depart: '2025-07-19',
        heure_depart: '17:00:00',
        lieu_depart: 'Montauban',
        date_arrivee: '2025-07-19',
        heure_arrivee: '21:00:00',
        lieu_arrivee: 'Albi',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 5,
        voiture_id: 9,
        utilisateur_id: 9,
      },
      {
        date_depart: '2025-07-20',
        heure_depart: '12:00:00',
        lieu_depart: 'Albi',
        date_arrivee: '2025-07-20',
        heure_arrivee: '16:00:00',
        lieu_arrivee: 'Carcassonne',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 4,
        voiture_id: 10,
        utilisateur_id: 10,
      },
      {
        date_depart: '2025-07-21',
        heure_depart: '08:00:00',
        lieu_depart: 'Carcassonne',
        date_arrivee: '2025-07-21',
        heure_arrivee: '12:00:00',
        lieu_arrivee: 'Narbonne',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 4,
        voiture_id: 11,
        utilisateur_id: 11,
      },
      {
        date_depart: '2025-07-22',
        heure_depart: '14:00:00',
        lieu_depart: 'Narbonne',
        date_arrivee: '2025-07-22',
        heure_arrivee: '18:00:00',
        lieu_arrivee: 'Perpignan',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 14,
        voiture_id: 12,
        utilisateur_id: 12,
      },
      {
        date_depart: '2025-07-23',
        heure_depart: '16:00:00',
        lieu_depart: 'Perpignan',
        date_arrivee: '2025-07-23',
        heure_arrivee: '20:00:00',
        lieu_arrivee: 'Montpellier',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 12,
        voiture_id: 13,
        utilisateur_id: 13,
      },
      {
        date_depart: '2025-07-24',
        heure_depart: '09:00:00',
        lieu_depart: 'Montpellier',
        date_arrivee: '2025-07-24',
        heure_arrivee: '13:00:00',
        lieu_arrivee: 'Avignon',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 7,
        voiture_id: 14,
        utilisateur_id: 14,
      },
      {
        date_depart: '2025-07-25',
        heure_depart: '11:00:00',
        lieu_depart: 'Avignon',
        date_arrivee: '2025-07-25',
        heure_arrivee: '15:00:00',
        lieu_arrivee: 'Valence',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 12,
        voiture_id: 15,
        utilisateur_id: 15,
      },
      {
        date_depart: '2025-07-26',
        heure_depart: '15:00:00',
        lieu_depart: 'Valence',
        date_arrivee: '2025-07-26',
        heure_arrivee: '19:00:00',
        lieu_arrivee: 'Chambéry',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 10,
        voiture_id: 1,
        utilisateur_id: 1,
      },
      {
        date_depart: '2025-07-27',
        heure_depart: '10:00:00',
        lieu_depart: 'Chambéry',
        date_arrivee: '2025-07-27',
        heure_arrivee: '14:00:00',
        lieu_arrivee: 'Grenoble',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 5,
        voiture_id: 2,
        utilisateur_id: 2,
      },
      {
        date_depart: '2025-07-28',
        heure_depart: '13:00:00',
        lieu_depart: 'Grenoble',
        date_arrivee: '2025-07-28',
        heure_arrivee: '17:00:00',
        lieu_arrivee: 'Annecy',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 4,
        voiture_id: 3,
        utilisateur_id: 3,
      },
      {
        date_depart: '2025-07-29',
        heure_depart: '17:00:00',
        lieu_depart: 'Annecy',
        date_arrivee: '2025-07-29',
        heure_arrivee: '21:00:00',
        lieu_arrivee: 'Besançon',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 10,
        voiture_id: 4,
        utilisateur_id: 4,
      },
      {
        date_depart: '2025-07-30',
        heure_depart: '12:00:00',
        lieu_depart: 'Besançon',
        date_arrivee: '2025-07-30',
        heure_arrivee: '16:00:00',
        lieu_arrivee: 'Dijon',
        statut: 'ouvert',
        nb_place: 3,
        prix_personne: 9,
        voiture_id: 5,
        utilisateur_id: 5,
      },
    ],
  });

  // Avis
  await prisma.avis.createMany({
    data: [
      { commentaire: 'Super trajet !', note: '5', statut: 'valide', utilisateur_id: 2 },
      { commentaire: 'Ponctuel et sympa', note: '4', statut: 'valide', utilisateur_id: 1 },
      { commentaire: 'Voiture propre', note: '5', statut: 'valide', utilisateur_id: 3 },
      { commentaire: 'Conducteur prudent', note: '4', statut: 'valide', utilisateur_id: 4 },
      { commentaire: 'Bonne ambiance', note: '5', statut: 'valide', utilisateur_id: 5 },
      { commentaire: 'Retard au départ', note: '3', statut: 'en attente', utilisateur_id: 6 },
      { commentaire: 'Trajet agréable', note: '5', statut: 'valide', utilisateur_id: 7 },
      { commentaire: 'Musique trop forte', note: '2', statut: 'en attente', utilisateur_id: 8 },
      { commentaire: 'Chauffeur très gentil', note: '5', statut: 'valide', utilisateur_id: 9 },
      { commentaire: 'A recommander', note: '5', statut: 'valide', utilisateur_id: 10 },
    ],
  });
}

main()
  .then(() => {
    console.log('Seed terminé !');
    return prisma.$disconnect();
  })
  .catch(e => {
    console.error(e);
    return prisma.$disconnect();
  });
